/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controller.EquipeController;
import controller.LoginController;
import controller.PessoaController;
import controller.RastreamentoController;
import controller.RequisitoController;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.pessoa;
import model.projeto;
import model.rel_pessoa_equipe;
import model.requisito;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author matheus
 */
public class TelaGerenciarProjeto extends CriadorTelas {

    /**
     * Creates new form TelaGerenciarProjeto
     */
    private projeto Projeto;

    private static TelaGerenciarProjeto instance;

    private TelaGerenciarProjeto() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public static synchronized TelaGerenciarProjeto getInstance() {
        if (instance == null) {
            instance = new TelaGerenciarProjeto();
        }
        return instance;
    }

    public void setProjeto(projeto Projeto) {
        this.Projeto = Projeto;
    }

    public projeto getProjeto() {
        return this.Projeto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(17, 222, 251));
        jDesktopPane1.setForeground(new java.awt.Color(205, 215, 217));
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(10, 10, 1270, 620);

        jMenu5.setText("Requisitos");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Alterar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Rastrear");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Relacionar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar2.add(jMenu5);

        jMenu2.setText("Pessoas");

        jMenuItem5.setText("Adicionar relação Pessoa / Requisito");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Gerenciar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Relatório");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Gerar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        setBounds(0, 0, 1291, 692);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        retornaTelaAnterior();
        instance = null;
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        pessoa logado = PessoaController.getInstance().returnPesLogin();
        rel_pessoa_equipe rel_pes = EquipeController.getInstance().retornaRelPessoaEqpByIdpessoa(logado.getIdpessoa());
        boolean permissao = RastreamentoController.getInstance().verificaPermissao(Projeto.getIdprojeto(), logado.getIdpessoa(), rel_pes.getIdfuncao());

        if (permissao) {
            List<rel_pessoa_equipe> listPess_Eqp = EquipeController.getInstance().retornaListaDeRelPessoasEquipeByIdequipe(Projeto.getIdequipe());
            if (listPess_Eqp != null) {
                TelaCadastrarRequisito.getInstance().setVisible(true);
                TelaCadastrarRequisito.getInstance().setPane(jDesktopPane1);
                jDesktopPane1.add(TelaCadastrarRequisito.getInstance());
            } else {
                int cadastrar = JOptionPane.showConfirmDialog(null, "Você não possui nenhuma pessoa cadastrada na equipe, deseja fazer isso agora?", "Membros da Equipe", JOptionPane.YES_NO_OPTION);
                if (cadastrar == 0) {
                    TelaIncluirPessoaEquipe.getInstance().setInterceptor(this);
                    TelaIncluirPessoaEquipe.getInstance().setEqp(EquipeController.getInstance().retornaEquipeById(Projeto.getIdequipe()));
                    TelaIncluirPessoaEquipe.getInstance().setVisible(true);
                    TelaIncluirPessoaEquipe.getInstance().initialize();
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        List<requisito> listRq = RequisitoController.getInstance().retornaListaRequisitosByIdprojeto(Projeto.getIdprojeto());
        if (listRq != null) {
            TelaRastrearRequisito.getInstance().setVisible(true);
            TelaRastrearRequisito.getInstance().setPane(jDesktopPane1);
            jDesktopPane1.add(TelaRastrearRequisito.getInstance());
        } else {
            int cadastrar = JOptionPane.showConfirmDialog(null, "Nenhum requisito cadastrado para este projeto, deseja fazer agora?", "Cadastrar requisito", JOptionPane.YES_NO_OPTION);
            if (cadastrar == 0) {
                TelaCadastrarRequisito.getInstance().setVisible(true);
                TelaCadastrarRequisito.getInstance().setPane(jDesktopPane1);
                jDesktopPane1.add(TelaCadastrarRequisito.getInstance());
            }
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        TelaSelecionarRequisito.getInstance().setProjeto(Projeto);
        TelaSelecionarRequisito.getInstance().setPane(jDesktopPane1);
        TelaSelecionarRequisito.getInstance().initialize();
        TelaSelecionarRequisito.getInstance().setVisible(true);
        jDesktopPane1.add(TelaSelecionarRequisito.getInstance());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaSelecionarRequisitoEditar.getInstance().setProjeto(Projeto);
        TelaSelecionarRequisitoEditar.getInstance().initialize();
        TelaSelecionarRequisitoEditar.getInstance().setPane(jDesktopPane1);
        TelaSelecionarRequisitoEditar.getInstance().setVisible(true);
        jDesktopPane1.add(TelaSelecionarRequisitoEditar.getInstance());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        TelaSelecionarRequisitoPessoa.getInstance().setProjeto(Projeto);
        TelaSelecionarRequisitoPessoa.getInstance().setPane(jDesktopPane1);
        TelaSelecionarRequisitoPessoa.getInstance().initialize();
        TelaSelecionarRequisitoPessoa.getInstance().setVisible(true);
        jDesktopPane1.add(TelaSelecionarRequisitoPessoa.getInstance());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        TelaGerenciarRelacionamentoReq.getInstance().setProjeto(Projeto);
        TelaGerenciarRelacionamentoReq.getInstance().setPane(jDesktopPane1);
        TelaGerenciarRelacionamentoReq.getInstance().initialize();
        TelaGerenciarRelacionamentoReq.getInstance().setVisible(true);
        jDesktopPane1.add(TelaGerenciarRelacionamentoReq.getInstance());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/engenharia_software?zeroDateTimeBehavior=convertToNull","root","");
            InputStream is = getClass().getResourceAsStream("Relatorio.jrxml");
            JasperReport jasperxml = JasperCompileManager.compileReport(is);
            JasperPrint printReport = JasperFillManager.fillReport(jasperxml, null, conn);
            JasperViewer view = new JasperViewer(printReport, false);
            view.setTitle("Ficha de protocolo");
            view.setVisible(true);
            conn.close();
        } catch (JRException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarProjeto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
