/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controller.EquipeController;
import controller.LoginController;
import controller.PessoaController;
import controller.RastreamentoController;
import java.util.List;
import javax.swing.JOptionPane;
import model.pessoa;
import model.projeto;
import model.rel_pessoa_equipe;

/**
 *
 * @author matheus
 */
public class TelaGerenciarProjeto extends CriadorTelas{

    /**
     * Creates new form TelaGerenciarProjeto
     */
    private projeto Projeto;
    
    
    private static TelaGerenciarProjeto instance;
    private TelaGerenciarProjeto() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public static synchronized TelaGerenciarProjeto getInstance(){
        if(instance == null){
            instance = new TelaGerenciarProjeto();
        }
        return instance;
    }

    public void setProjeto(projeto Projeto){
        this.Projeto = Projeto;
    }
    public projeto getProjeto(){
        return this.Projeto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 720, 380);

        jMenu5.setText("Requisitos");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Alterar");
        jMenu5.add(jMenuItem2);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        setBounds(0, 0, 711, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        retornaTelaAnterior();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        pessoa logado = PessoaController.getInstance().returnPesLogin();
        rel_pessoa_equipe rel_pes = EquipeController.getInstance().retornaRelPessoaEqpByIdpessoa(logado.getIdpessoa());
        boolean permissao =  RastreamentoController.getInstance().verificaPermissao(Projeto.getIdprojeto(), rel_pes.getIdpessoa(), rel_pes.getIdfuncao());
       
        if(permissao){
            List<rel_pessoa_equipe> listPess_Eqp = EquipeController.getInstance().retornaListaDeRelPessoasEquipeByIdequipe(Projeto.getIdequipe());
            if(listPess_Eqp != null){
                TelaCadastrarRequisito.getInstance().setInterceptor(this);
                TelaCadastrarRequisito.getInstance().setVisible(true);
                TelaCadastrarRequisito.getInstance().setPanel(jDesktopPane1);
                jDesktopPane1.add(TelaCadastrarRequisito.getInstance());
            }else{
                int cadastrar = JOptionPane.showConfirmDialog(null, "Você não possui nenhuma pessoa cadastrada na equipe, deseja fazer isso agora?","Menbros da Equipe",JOptionPane.YES_NO_OPTION);
                if(cadastrar == 0){
                    TelaIncluirPessoaEquipe.getInstance().setInterceptor(this);
                    TelaIncluirPessoaEquipe.getInstance().setEqp(EquipeController.getInstance().retornaEquipeById(Projeto.getIdequipe()));
                    TelaIncluirPessoaEquipe.getInstance().setVisible(true);
                    TelaIncluirPessoaEquipe.getInstance().initialize();
                    this.setVisible(false);
                }
           }
       }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarProjeto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
